use_frameworks!

platform :ios, '10.0'

target 'Example_UIKit' do
  pod 'FriendlyCaptcha', :path => '../'

  target 'FriendlyCaptcha_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 5.0.0'
    pod 'Nimble', '~> 10.0.0'
  end
end

target 'Example_SwiftUI' do
  pod 'FriendlyCaptcha', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
