name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: select xcode version
        run: sudo xcodes select 15.1 && xcodebuild -version

      - name: install pods
        run: pod install
        working-directory: Example

      - name: run tests
        run: |
          set -o pipefail && \
          xcodebuild test \
            -enableCodeCoverage YES \
            -workspace Example/FriendlyCaptcha.xcworkspace \
            -scheme Example_UIKit \
            -sdk iphonesimulator17.2 \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' | xcbeautify --renderer github-actions
